
export const ADMIN_ADD_POST_REQUEST = 'ADMIN_ADD_POST_REQUEST';
export const ADMIN_ADD_POST_SUCCESS = 'ADMIN_ADD_POST_SUCCESS';
export const ADMIN_ADD_POST_FAILURE = 'ADMIN_ADD_POST_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_ADD_POST_REQUEST = 'USER_ADD_POST_REQUEST';
export const USER_ADD_POST_SUCCESS = 'USER_ADD_POST_SUCCESS';
export const USER_ADD_POST_FAILURE = 'USER_ADD_POST_FAILURE';

export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';